#- name: Create Sudo User
#  user: name=docker
#        groups=sudo
#        shell=/bin/bash
#        state=present
#
#- name: Set Passwordless SSH Access for docker user
#  copy: src=sudoers
#        dest=/etc/sudoers.d
#        mode=0440


- name: Install dependancies
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes
- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
- name: check install
  service:
    name: docker
    state: started
    enabled: yes
